<div class="container">
<div align="center">

<br><br><br><br><br>
  <div class="reacts">
  <div class="circle"><img src="assets/img/emojis/like.png" alt=""/>
    <p>Acertou</p>
  </div>
  <div class="circle"><img src="assets/img/emojis/like.png" alt=""/>
    <p>Acertou</p>
  </div>
   <div class="circle"><img src="assets/img/emojis/like.png" alt=""/>
    <p>Acertou</p>
  </div>
   <div class="circle"><img src="assets/img/emojis/sad.png" alt=""/>
    <p>Errou</p>
  </div>
   <div class="circle"><img src="assets/img/emojis/like.png" alt=""/>
    <p>Acertou</p>
  </div>
   <div class="circle"><img src="assets/img/emojis/sad.png" alt=""/>
    <p>Errou</p>
  </div>
   <div class="circle"><img src="assets/img/emojis/like.png" alt=""/>
    <p>Acertou</p>
  </div>
   <div class="circle"><img src="assets/img/emojis/sad.png" alt=""/>
    <p>Errou</p>
  </div>
   <div class="circle"><img src="assets/img/emojis/like.png" alt=""/>
    <p>Acertou</p>
  </div>
  <div class="circle"><img src="assets/img/emojis/sad.png" alt=""/>
    <p>Errou</p>
  </div>
</div>
</div>
</div>