<div class="container">

    <div class="row">
        <div class="col s12 m12">
            <div class="card-panel laranja" style="">
                <span class="white-text"><h5><a href="menu"><i class="fa fa-users" aria-hidden="true" style="font-size: 1em; color: #fff"></i></a> Criadores do projeto</h5></span>
            </div>
        </div>
    </div>

<!--
    <ul class="collection">
        <li class="collection-item avatar">
            <img src="../assets/img/icone.png" alt="" class="circle">
            <span class="title"><b>Programador</b></span>
            <p>Felipe Novais o foda do back-end</p>
            <div class="secondary-content"><i class="fa fa-code" aria-hidden="true" style="font-size: 1.9em"></i></div>
        </li>
        <li class="collection-item avatar">
            <img src="images/yuna.jpg" alt="" class="circle">
            <span class="title"><b>Programador(HTML naõ é programação)</b></span>
            <p>Vinnicius Gomes o merdinha do front-end</p>
            <div class="secondary-content"><i class="fa fa-code" aria-hidden="true" style="font-size: 1.9em"></i></div>
        </li>
        <li class="collection-item avatar">
            <img src="images/yuna.jpg" alt="" class="circle">
            <span class="title"><b>Professora</b></span>
            <p>First Line</p>
            <div class="secondary-content"><i class="material-icons" style="font-size: 2em">school</i></div>
        </li>
        <li class="collection-item avatar">
            <img src="images/yuna.jpg" alt="" class="circle">
            <span class="title"><b>Professora</b></span>
            <p>First Line</p>
            <div class="secondary-content"><i class="material-icons" style="font-size: 2em">school</i></div>
        </li>
        <li class="collection-item avatar">
            <img src="images/yuna.jpg" alt="" class="circle">
            <span class="title"><b>Professora</b></span>
            <p>First Line</p>
            <div class="secondary-content"><i class="material-icons" style="font-size: 2em">school</i></div>
        </li>
        <li class="collection-item avatar">
            <img src="images/yuna.jpg" alt="" class="circle">
            <span class="title"><b>Professora</b></span>
            <p>First Line</p>
            <div class="secondary-content"><i class="material-icons" style="font-size: 2em">school</i></div>
        </li>
    </ul>
-->

    <div align="center"><br>
        <a href="login" class=" s12 btn-floating btn-large waves-effect waves-light laranja"><i class="material-icons">arrow_back</i></a><br>
        <a style="color: #FFF">Voltar</a>
    </div>

</div>