<div class="splash">
</div>
<div class="container2">

    <div class="start-game game-full-flex" id="start-game">

        <div class="start-game-top"><a class="play-full-page" href="https://codepen.io/gregh/full/yVLOyO/" target="_blank">Full Page Mode</a></div>

        <div class="logo-holder">
            <p class="logo">
                <span>C</span>
                <span>o</span>
                <span>l</span>
                <span>o</span>
                <span>r</span>
                <span>o</span>
                <span>n</span>
            </p>
            <a class="play-button" href="#" onclick="game.start()">Jogar</a>
            <h4 class="hint">A bola sempre começa na cor <span>Vermelha</span></h4>
        </div>

        <div class="how-to-play">
            <div class="section section-1">
                <h4>A bola muda de cor<br>toda vez que pula.</h4>
                <div class="content">
                    <div class="ball-demo" id="ball-demo"></div>
                </div>
            </div>
            <div class="section section-2">
                <h4>Clique na barra para alternar as cores<br>(Vermelho, Amarelo, Roxo)</h4>
                <div class="content">
                    <div class="bar bar-1" data-index="0"></div>
                    <div class="bar bar-2"></div>
                    <div class="bar bar-3"></div>
                </div>
            </div>
            <div class="section section-3">
                <h4>A bola sempre tem que<br>estar da mesma cor que a barra</h4>
                <div class="content">
                    <div class="ball-demo" id="ball-demo"></div>
                    <div class="bar bar-1"></div>
                </div>
            </div>
        </div>

    </div>

    <div class="stop-game game-full-flex">

        <div class="score-container2">

            <h1>Pontuação</h1><br>

            <div class="final-score"></div><br>
            <div class="result"></div><br>

            <div>
                <a class="play-again" href="#" onclick="game.start()">Jogar</a>
                <a class="main-menu" href="#" onclick="game.intro()">Menu</a>
            </div>

        </div>

    </div>

    <div class="small-glows"></div>

    <div class="glow">
        <div class="sun"></div>
    </div>

    <div class="waves">
        <div class="top_wave"></div>
        <div class="wave1"></div>
        <div class="wave2"></div>
        <div class="wave3"></div>
        <div class="wave4"></div>
    </div>

    <div class="mounts">
        <div class="mount1"></div>
        <div class="mount2"></div>
    </div>

    <div class="clouds"></div>

    <div class="scene">
        <div class="learn-to-play">Clique nas barras para mudar a cor!</div>
        <div class="score" id="score"></div>
        <div class="ball-holder"></div>
        <div class="sticks" id="sticks"></div>
    </div>

    <div class="noise"></div>

</div>
