<!DOCTYPE html>

<html lang="pt-BR">

<head>
    <!-- adicionado apos erro do servidor -->
    <base href="/<?php echo $baseUrl ?>" />
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!--  Icone  -->
    <link rel="icon" type="image/png" href="assets/img/icones/icone.png">
    <meta name="msapplication-TileColor" content="#00305F">
    <meta name="theme-color" content="#00305F">

    <!--  Fonts  -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css" >
    <link rel="stylesheet" type="text/css" href="assets/css/font.min.css">
   
    <!--  CSS  -->
    <link rel="stylesheet" href="assets/css/materialize.min.css" media="screen,projection">
    <link rel="stylesheet" href="assets/css/style.min.css" media="screen,projection">
    
    <title>
        <?= $title ?>
    </title>

</head>

<body>

    <section>
        <?php $this->controller->renderView(); ?>
    </section>

</body>

<!-- Importação dos scripts -->
<script type="text/javascript" src="assets/js/jquery-3.2.1.min.js"></script>
<script type="text/javascript" src="assets/js/materialize.min.js"></script>

</html>