<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <base href="/<?php echo $baseUrl ?>" />
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/png" href="assets/img/icones/icone.png">
    <meta name="msapplication-TileColor" content="#00305F">
    <meta name="theme-color" content="#00305F">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="assets/css/materialize.min.css">
    <link rel="stylesheet" type="text/css" href="assets/css/font.min.css">
    <link rel="stylesheet" href="assets/css/style.min.css">
    <title>
        <?=$title ?>
    </title>
</head>

<body>
    <section>
        <?php $this->controller->renderView(); ?> </section>
</body>
<script type="text/javascript" src="assets/js/jquery-3.2.1.min.js"></script>
<script type="text/javascript" src="assets/js/materialize.min.js"></script>

</html>
