<?php if(!isset($_SESSION['questao'])){$_SESSION['questao'] = 1; } ?>
<body onLoad="relogio()">
    
    <iframe width="0" height="0" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/251533794&amp;color=%23ff5500&amp;auto_play=true&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;show_teaser=true&amp;visual=true"></iframe>
    
	<script language="javaScript">
		var min, seg;
		min = 3;
		seg = 1;

		function relogio() {
			if ((min > 0) || (seg > 0)) {
				if (seg == 0) {
					seg = 59;
					min = min - 1
				} else {
					seg = seg - 1;
				}
				if (min.toString().length == 1) {
					min = "0" + min;
				}
				if (seg.toString().length == 1) {
					seg = "0" + seg;
				}
				document.getElementById('spanRelogio').innerHTML = min + ":" + seg;
				setTimeout('relogio()', 1000);
			} else {
				document.getElementById('spanRelogio').innerHTML = "00:00";
				document.respostas.submit();
			}
		}
	</script>
	<div class="container">
		<div align="center">
			<div class="section"></div>
			<div class="reacts">
			<?php
                for($i=0; $i < 10; $i++){
                    $p = "p".$i;
                    if($_SESSION[$p] == 0){
                        echo "<div class='circle'><img src='assets/img/emojis/quiz.png' alt='' />
					               <p>".($i+1)."</p>
				            </div>";
                    }elseif($_SESSION[$p] == 1){
                        echo "<div class='circle'><img src='assets/img/emojis/like.png' alt='' />
					               <p>Acertou</p>
				            </div>";
                    }else{
                        echo "<div class='circle'><img src='assets/img/emojis/sad.png' alt='' />
					               <p>Errou</p>
				            </div>";
                    }
                }    
            ?>
			</div>
		</div>
		<div class="section"></div>
		<div class="section">
			<div class="row">
				<h4 class="col s6 m6" style="color: #FFF">Questão <?php echo $_SESSION['questao']?></h4>
				<h5 class="col s6 m6" style="font-weight: 300; text-align: right; color: #FFF; font-size: 1.2em;" id="spanRelogio"></h5>
			</div>
			<div class="divider" style="color: #fff"></div>
		</div>
		<?php $pergunta = new BuscarPergunta(); $enunciado = $pergunta->buscar(); $id = $_SESSION['id_perg']; ?>
		<div class="col s5 m5">
			<p class="col s5 m5" style="text-align: center; max-width: 100%; color: #FFF; font-size: 1.2em;"><?php echo $enunciado; ?> </p><br><br>
		</div><br>
		<p style="font-weight: 300; text-align: left; color: #FFF">Escolha a alternativa correta:</p><br>
		<form action="resposta" name="respostas" method="post" autocomplete="off">
			<div class="row">
				<div class="col s5 m5">
					<?php $pergunta->alternativas($id); ?> </div>
			</div><br>
			<button type="submit" class="col s12 m12 btn waves-effect laranja">Próxima</button>
		</form>
        
        
        
        
	</div>
</body>
